---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(rvest)

live_session <- html_session("http://ireports.wrapsnet.org/Interactive-Reporting/EnumType/Report?ItemPath=/rpt_WebArrivalsReports/MX%20-%20Arrivals%20for%20a%20Demographic%20Profile") 

html_form(live_session) %>% 
  set_values("dnn$ctr513$View$ReportViewer1$ctl04$ctl03$ddValue" = "1")


read_html("http://ireports.wrapsnet.org/Interactive-Reporting/EnumType/Report?ItemPath=/rpt_WebArrivalsReports/MX%20-%20Arrivals%20for%20a%20Demographic%20Profile") %>% 
  html_nodes("#dnn_ctr513_View_ReportViewer1_ctl04_ctl07_ddValue") %>% 
  html_children() %>% 
  html_attr("value")

read_html("http://ireports.wrapsnet.org/Interactive-Reporting/EnumType/Report?ItemPath=/rpt_WebArrivalsReports/MX%20-%20Arrivals%20for%20a%20Demographic%20Profile") %>% 
  html_nodes("#dnn_ctr513_View_ReportViewer1_ctl04_ctl07_ddValue") %>% 
  html_children() %>% 
  html_text()
```



```{r}
url <- "http://www.footballoutsiders.com/stats/snapcounts"
pgsession <- html_session(url)
pgform <-html_form(pgsession)[[3]]


filled_form <-set_values(pgform,
            "team" = "ALL",
            "week" = "1",
            "pos"  = "ALL",
            "year" = "2015"             
 )

d <- submit_form(session=pgsession, form=filled_form)

d
```

```{r}
library(seleniumPipes)
library(RSelenium) # start a server with utility function
selServ <- RSelenium::rsDriver()
remDr <- remoteDr(port = 4445)
remDr %>% go(url = "http://ireports.wrapsnet.org/Interactive-Reporting/EnumType/Report?ItemPath=/rpt_WebArrivalsReports/MX%20-%20Arrivals%20for%20a%20Demographic%20Profile")

shell('docker run -d -p 4445:4444 selenium/standalone-firefox')
remDr <- remoteDriver(remoteServerAddr = "localhost", port = 4445L, browserName = "firefox")
remDr$open()
```

